CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT       NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(64)  NOT NULL,
    email      VARCHAR(32)  NOT NULL,
    password   VARCHAR(256) NOT NULL,
    user_role  VARCHAR(32)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT login_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID         CHAR(36)       NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200)  NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
);

CREATE TABLE IF NOT EXISTS SPRING_SESSION
(
    PRIMARY_ID         CHAR(36)       NOT NULL,
    SESSION_ID CHAR(36)   NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    PRIMARY KEY (PRIMARY_ID),
    CONSTRAINT session_id_unique UNIQUE (SESSION_ID)
);

COMMIT;